# name: CD

# on:
#   push:
#     branches:
#       - main
      
#   schedule:
#     - cron: '0 0 * * *'  # This runs at 00:00 UTC every day

# env:
#   DBT_PROFILES_DIR: .
#   DBT_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
#   DBT_DATASET: ${{ secrets.PROD }}
#   DBT_LOCATION: ${{ secrets.LOCATION }}

# jobs:
#   dbt-cd:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@v0.2.1
#       with:
#         project_id: ${{ secrets.GCP_PROJECT_ID }}
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Run dbt commands
#       run: |
#         dbt debug --profiles-dir . --project-dir . --target prod
#         dbt deps --profiles-dir . --project-dir .
#         dbt build --profiles-dir . --project-dir . --target prod

#     - name: Cleanup
#       if: always()
#       run: rm -f /tmp/sa_key.json
