name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DBT_PROFILES_DIR: .
  DBT_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  DBT_DATASET: ${{ secrets.DEV }}
  DBT_LOCATION: ${{ secrets.LOCATION }}

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Run sqlfmt
      run: |
        sqlfmt models/
  
    # - name: Run sqlfluff
    #   run: |
    #     sqlfluff lint models/
    #     sqlfluff fix models/ --force

    - name: Run dbt commands
      run: |
        dbt debug --profiles-dir . --project-dir . --target dev
        dbt deps --profiles-dir . --project-dir .
        dbt test --profiles-dir . --project-dir . --target dev
        dbt run --profiles-dir . --project-dir . --target dev

    - name: Cleanup
      if: always()
      run: rm -f /tmp/sa_key.json