name: docs_update

on:
  push:
    branches:
      - "main"

env:
  DBT_PROFILES_DIR: .
  DBT_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  DBT_DATASET: ${{ secrets.DEV }}
  DBT_LOCATION: ${{ secrets.LOCATION }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  scheduled_run:
    name: docs_update
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery
          dbt deps

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Checkout docs branch
        run: |
          git checkout -b docs origin/main

      - name: Generate dbt docs
        run: dbt docs generate --target prod

      - name: Move files to docs directory
        run: |
          mkdir -p ./docs
          cp target/{catalog.json,manifest.json,index.html} docs/

      - name: Clean up target directory
        run: dbt clean

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: |
          git config user.email "abc@xyz"  # replace with the actual email you want to use for the commits
          git config user.name "github-actions"
          git commit -am "Auto-update docs"

      - name: Push changes to docs
        run: |
          git push -f --set-upstream origin docs