dbt-sweeplift:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: sweeplift
      dataset: dev 
      threads: 4  
      OPTIONAL_CONFIG: VALUE

    prod:
      type: bigquery
      method: oauth
      project: sweeplift
      dataset: prod 
      threads: 4  
      OPTIONAL_CONFIG: VALUE

  target: dev
  